// Mocks generated by Mockito 5.4.6 from annotations
// in inventory/test/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i5;

import 'package:inventory/models/product.dart' as _i3;
import 'package:inventory/providers/inventory_provider.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [InventoryProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockInventoryProvider extends _i1.Mock implements _i2.InventoryProvider {
  MockInventoryProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i3.Product> get products =>
      (super.noSuchMethod(
            Invocation.getter(#products),
            returnValue: <_i3.Product>[],
          )
          as List<_i3.Product>);

  @override
  _i2.DataState get dataState =>
      (super.noSuchMethod(
            Invocation.getter(#dataState),
            returnValue: _i2.DataState.loading,
          )
          as _i2.DataState);

  @override
  int get totalProducts =>
      (super.noSuchMethod(Invocation.getter(#totalProducts), returnValue: 0)
          as int);

  @override
  int get totalQuantity =>
      (super.noSuchMethod(Invocation.getter(#totalQuantity), returnValue: 0)
          as int);

  @override
  int get outOfStockProducts =>
      (super.noSuchMethod(
            Invocation.getter(#outOfStockProducts),
            returnValue: 0,
          )
          as int);

  @override
  List<String> get categories =>
      (super.noSuchMethod(
            Invocation.getter(#categories),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  int get categoryCount =>
      (super.noSuchMethod(Invocation.getter(#categoryCount), returnValue: 0)
          as int);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  List<_i3.Product> getFilteredProducts(
    String? searchQuery,
    String? category,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getFilteredProducts, [searchQuery, category]),
            returnValue: <_i3.Product>[],
          )
          as List<_i3.Product>);

  @override
  _i4.Future<void> addProduct(_i3.Product? product) =>
      (super.noSuchMethod(
            Invocation.method(#addProduct, [product]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateProduct(_i3.Product? product) =>
      (super.noSuchMethod(
            Invocation.method(#updateProduct, [product]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteProduct(String? productId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProduct, [productId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
