// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKqyxE-WomJb7MHTm2QRVX_6FIlEWajho',
    appId: '1:785123061936:web:b0e782a226d1f24ca44b75',
    messagingSenderId: '785123061936',
    projectId: 'cse464',
    authDomain: 'cse464.firebaseapp.com',
    storageBucket: 'cse464.firebasestorage.app',
    measurementId: 'G-4M1L7V5ZGX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVOVjBZF-cVOfPWNyoEHQDnaVefTOFzSI',
    appId: '1:785123061936:android:7c38a649a5cedfcba44b75',
    messagingSenderId: '785123061936',
    projectId: 'cse464',
    storageBucket: 'cse464.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPNjsHJn1qZnexp-Vls0vPllQBldrUQsQ',
    appId: '1:785123061936:ios:a6b0a0b2aea33f64a44b75',
    messagingSenderId: '785123061936',
    projectId: 'cse464',
    storageBucket: 'cse464.firebasestorage.app',
    iosBundleId: 'com.shop0.inventory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPNjsHJn1qZnexp-Vls0vPllQBldrUQsQ',
    appId: '1:785123061936:ios:a6b0a0b2aea33f64a44b75',
    messagingSenderId: '785123061936',
    projectId: 'cse464',
    storageBucket: 'cse464.firebasestorage.app',
    iosBundleId: 'com.shop0.inventory',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKqyxE-WomJb7MHTm2QRVX_6FIlEWajho',
    appId: '1:785123061936:web:05561acdc0fa0a95a44b75',
    messagingSenderId: '785123061936',
    projectId: 'cse464',
    authDomain: 'cse464.firebaseapp.com',
    storageBucket: 'cse464.firebasestorage.app',
    measurementId: 'G-KF16D9KXEK',
  );
}
